# .goreleaser.yaml
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: brightmoon

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/brightmoon/main.go
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - zip
      - tar.gz
    format_overrides:
      - goos: windows
        formats: [zip]
      - goos: darwin
        formats: [zip]
      - goos: linux
        formats: [tar.gz]
    name_template: "{{ .ProjectName }}-{{.Major}}.{{.Minor}}.{{.Patch}}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-dev.{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:' 

release:
  name_template: "v{{.Major}}.{{.Minor}}.{{.Patch}}-brightmoon" 